
//Status of Ingredients 
const ADDINGREDIENT='ADDINGREDIENT';
const REMOVEINGREDIENT='REMOVEINGREDIENT';
const SETINGREDIENTS='SETINGREDIENTS';
const FETCHINGREDIENTSERROR='FETCHINGREDIENTSERROR';

//Purchase the burger
const PURCHASEBURGERSUCCESS='PURCHASEBURGERSUCCESS';
const PURCHASEBURGERFAIL='PURCHASEBURGERFAIL';
const PURCHASEBURGERSTART='PURCHASEBURGERSTART';
const PURCHASEBURGER='PURCHASEBURGER';
const PURCHASEINIT='PURCHASEINIT';

//Fetching the order from firebase
const FETCHORDERSUCCESS='FETCHORDERSUCCESS';
const FETCHORDERFAIL='FETCHORDERFAIL';
const FETCHORDERSTART='FETCHORDERSTART';

//Authentication actions
const AUTH_START='AUTH_START';
const AUTH_SUCCESS='AUTH_SUCCESS';
const AUTH_FAIL='AUTH_FAIL';
const AUTH_LOGOUT='AUTH_LOGOUT';


export {ADDINGREDIENT,REMOVEINGREDIENT,SETINGREDIENTS,FETCHINGREDIENTSERROR,
    PURCHASEBURGERSUCCESS,PURCHASEBURGERFAIL,PURCHASEBURGERSTART,PURCHASEBURGER,PURCHASEINIT,
    FETCHORDERSUCCESS,FETCHORDERFAIL,FETCHORDERSTART,
    AUTH_START,AUTH_SUCCESS,AUTH_FAIL,AUTH_LOGOUT};