const ADDINGREDIENT='ADDINGREDIENT';
const REMOVEINGREDIENT='REMOVEINGREDIENT';
const SETINGREDIENTS='SETINGREDIENTS';
const FETCHINGREDIENTSERROR='FETCHINGREDIENTSERROR';

const PURCHASEBURGERSUCCESS='PURCHASEBURGERSUCCESS';
const PURCHASEBURGERFAIL='PURCHASEBURGERFAIL';
const PURCHASEBURGERSTART='PURCHASEBURGERSTART';
const PURCHASEBURGER='PURCHASEBURGER';

export {ADDINGREDIENT,REMOVEINGREDIENT,SETINGREDIENTS,FETCHINGREDIENTSERROR,
    PURCHASEBURGERSUCCESS,PURCHASEBURGERFAIL,PURCHASEBURGERSTART,PURCHASEBURGER};