const ADDINGREDIENT='ADDINGREDIENT';
const REMOVEINGREDIENT='REMOVEINGREDIENT';
const SETINGREDIENTS='SETINGREDIENTS';
const FETCHINGREDIENTSERROR='FETCHINGREDIENTSERROR';

export {ADDINGREDIENT,REMOVEINGREDIENT,SETINGREDIENTS,FETCHINGREDIENTSERROR};